### ISSUE TITLE
Remove dependency on strangelove docker repo

### ISSUE THREAD

**Issue by joe-bowman** [strangelove-ventures/ibc-test-framework#9]
There is currently a dependency on strangeloves docker repo, here:

[			Repository:     fmt.Sprintf("ghcr.io/strangelove-ventures/heighliner/%s", name),](https://github.com/strangelove-ventures/ibc-test-framework/blob/977f07b368abb310451f5ffb8cd15a9064993313/ibc/cosmos_chain.go#L59)

It would be great if a full docker image path (rather than `image:version`) is passed in, it doesn't get prefixed.

**Comment by agouin** [comment]
Resolved by #11
